import getSitemapResponse from '@/serverFns/public/getSitemap';
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/sitemap.xml')({
  // Return the Response generated by the serverFn directly
  loader: async () => {
    const resp = await getSitemapResponse();
    return resp;
  },
});
